### ISSUE TITLE
Handle an array of subscriptions?

### ISSUE THREAD

**Issue by misaizdaleka** [NetanelBasal/ngx-auto-unsubscribe#11]
Hey, 

How hard would it be for you to implement handling an array of subscriptions? 
I have a case where I have 3+ subscriptions, so I wouldn't wanna create a variable for each one of them. 

If you're too busy, I can give it a go. 

Thanks

**Comment by NetanelBasal** [comment]
What you are saying could work if we check that the property is an array and then if the values are subscriptions. ( I think it could be expensive unless you have something else in mind )

I would make it optional by passing a parameter to the decorator, something like:
```
@AutoUnsubscribe({
  includeArrays: true
})
```
I'd love to see PR.

**Comment by misaizdaleka** [comment]
#https://github.com/NetanelBasal/ngx-auto-unsubscribe/pull/12

**Comment by NetanelBasal** [comment]
Added in version 2.1.0.

**Comment by BBlackwo** [comment]
@NetanelBasal I like your idea:

>(Maybe we can force a name convention like **Subscriptions)

Then it doesn't have to loop through each property on the component? It could just loop through a `this.subscriptions` array. Thoughts?

**Comment by NetanelBasal** [comment]
Sounds good, would love to see a PR. :)

**Comment by misaizdaleka** [comment]
But it would also make sense to set the array name as option. So by default it would be subscriptions$ (or subscriptions), but user should be able to change that with an additional param.

**Comment by NetanelBasal** [comment]
@BBlackwo you should not prefix with $, it's subscriptions, not observables.
