### ISSUE TITLE
autounsubscribing block-scoped Observables

### ISSUE THREAD

**Issue by mateuszwitkowski** [NetanelBasal/ngx-auto-unsubscribe#13]
I know it's not a proper issue but rather a question about possible enhancement but is it possible in any way to modify this decorator so it would cover such cases like:

```
ngOnInit {
  Observable.fromEvent(window, 'dragend').subscribe();
}
```

```
ngOnInit {
  const subscription = Observable.fromEvent(window, 'dragend').subscribe();
}
```

**Comment by NetanelBasal** [comment]
Unfortunately not, but for this cases, you can use https://github.com/NetanelBasal/ngx-take-until-destroy
