### ISSUE TITLE
Filter for Subject

### ISSUE THREAD

**Issue by toxik** [NetanelBasal/ngx-auto-unsubscribe#16]
Is there any way to filter the Subject objects ?
These also have an unsubscribe() method although they're not of type Subscription.

**Comment by NetanelBasal** [comment]
Why do u need to filter them? A Subject is also an Observable, it should be unsubscribed when the component destroyed.

**Comment by toxik** [comment]
Right, but a Subscription is not an Observable, not sure what the connection is here :)
So if I have a `Subscription` on a `Subject` that got its `unsubscribe()`called then I get an error when I try to unsubscribe the `Subscription` of that `Subject`:

https://blog.angularindepth.com/rxjs-closed-subjects-1b6f76c1b63c

**Comment by NetanelBasal** [comment]
Did you face any problem with the decorator and your use case?

**Comment by toxik** [comment]
Ah no, it's fine, sorry. There was a bug in my code in fact :))
