### ISSUE TITLE
Seems like this is not working for Angular 5 

### ISSUE THREAD

**Issue by KalanaPerera** [NetanelBasal/ngx-auto-unsubscribe#18]
if anyone got same error?

**Comment by KalanaPerera** [comment]
I have used this for my new angular 5 projects, it's not working, basically not auto unsubscribing,
 
But the same library I have used for Angular 4 project, it's working. 

That's why I wanted to know, this issue having to others also or not

**Comment by NetanelBasal** [comment]
We are working with Angular 5 and all good. Can you show me the code, please?

**Comment by dayanandpharad** [comment]
Indeed! The code is working absolutely fine with angular 5 application without any room for issues.
