### ISSUE TITLE
Support universal

### ISSUE THREAD

**Issue by zorrme** [NetanelBasal/ngx-auto-unsubscribe#22]
Can we please do a platform check before using `window` ?

**Comment by NetanelBasal** [comment]
Sure. You want to add PR or I will do it when I have time?

**Comment by NetanelBasal** [comment]
Close. 2.4.1

**Comment by zorrme** [comment]
Thanks, but I did not see the change in master ?

**Comment by NetanelBasal** [comment]
Now you should.
