### ISSUE TITLE
AOT Build supported?

### ISSUE THREAD

**Issue by kqadem** [NetanelBasal/ngx-auto-unsubscribe#23]
Does this work with AOT?

**Comment by NetanelBasal** [comment]
Sure. The only thing you need to do is define the ngOnDestory method.

**Comment by kqadem** [comment]
ok, perfect 👍 Another question: 
here you do the check a second time, even though you did it in line 13. Is there a reason behind it?

**Comment by NetanelBasal** [comment]
Nope, it can be cached.
