### ISSUE TITLE
Base class usage not possible with angular 5

### ISSUE THREAD

**Issue by BorntraegerMarc** [NetanelBasal/ngx-auto-unsubscribe#26]
I've upgraded to angular 5 and to the latest version of this library and what I described in https://github.com/NetanelBasal/ngx-auto-unsubscribe/issues/4
is not possible any more. I don't receive an error in the console nor is the subscription unsubscribed.

I verified that the ngOndestroy is properly called and that the component is actually deleted.

PS: Using ionic in the project.

**Comment by BorntraegerMarc** [comment]
Hold on, I forgot to save the subscription in an attribute. Gimme a hour to add it

**Comment by BorntraegerMarc** [comment]
yeah it doesn't reproduce anymore after adding the subscription as an attribute. Trying with ionic now...

**Comment by BorntraegerMarc** [comment]
Re-opening again (sorry for spam)

But I figured it out. In this file https://stackblitz.com/edit/test-ngx-auto-unsubscribe?file=src%2Fapp%2Fhello.component.ts :

- If the sub class overrides `ngOnDestroy` from parent class the subscription will not be unsubscribed
- However if the sub class calls `super.ngOnDestroy()` then the subscriptions will be properly unsubscribed

In my opinion this is a bug: Subscriptions should not only be unsubscribed if the `ngOnDestroy` of the parent class is explicitly called.

I thought the whole point of introducing an empty `ngOnDestroy` is only so the functionality works even for AOT builds.

**Comment by NetanelBasal** [comment]
It's not a bug; it's a basic OOP. If you override a parent method, it will be called only if you call `super.method()`.

**Comment by BorntraegerMarc** [comment]
yeah that's true 😄 but I thought since it was only for AOT to pass it has no other meaning.

But since apparently it's the expected behaviour I'm closing this issue...

PS: Maybe one could mention this in the README :)
