### ISSUE TITLE
chceck instanceof

### ISSUE THREAD

**Issue by 5311O** [NetanelBasal/ngx-auto-unsubscribe#32]
https://github.com/NetanelBasal/ngx-auto-unsubscribe/blob/63cbbae3b9993dea61af75cba8a2616cc808f711/src/auto-unsubscribe.ts#L3

Why not just check with instanceof? Not sure what's duck typing here for

`const doUnsubscribe = sub => sub instanceof Subscription`

**Comment by NetanelBasal** [comment]
We can but then we couple the library to RxJs
