### ISSUE TITLE
Do I have to store all subscriptions in properties ?

### ISSUE THREAD

**Issue by rostamiani** [NetanelBasal/ngx-auto-unsubscribe#36]
Do I have to store the subscription to a variable to get it unsubscribed?
I used httpClient services in my project just like this:

```js
this.commerceService.getTotalList(this.listOptions).subscribe(
    // Do whatever
);
```
Do I have to store all subscriptions in properties ?

**Comment by NetanelBasal** [comment]
Yes, if you're not using the `array` option.
