### ISSUE TITLE
Doesn't unsubscribe in --prod builds unless class implements the ngOnDestroy method

### ISSUE THREAD

**Issue by stefda** [NetanelBasal/ngx-auto-unsubscribe#7]
Hi Netanel. I've come across a peculiar bug in my code that led me to realise the `AutoUnsubscribe` decorator doesn't trigger unsubscription unless the class it decorates explicitly implements the `OnDestroy` interface (and the required `ngOnDestroy` method). The reason, it seems, is that the [dynamically added ngOnDestroy](https://github.com/NetanelBasal/ngx-auto-unsubscribe/blob/master/src/ngx-auto-unsubscribe.ts#L6) gets "compiled out" when building with the `--prod` flag.

I was just wondering if you've come across the same issue or it's specific to my code setup. I'm on angular 2.4.3.

**Comment by NetanelBasal** [comment]
Hey, I think you missed the docs: 

```
  // If you work with AOT this method must be present, even if empty! 
  // Otherwise 'ng build --prod' will optimize away any calls to ngOnDestroy, 
  // even if the method is added by the @AutoUnsubscribe decorator
  ngOnDestroy() {
    // You can also do whatever you need here
  }
```

**Comment by stefda** [comment]
Haha, I did miss that. Thanks!
