### ISSUE TITLE
It whould be greate if there be global config for that.

### ISSUE THREAD

**Issue by FriOne** [NetanelBasal/ngx-auto-unsubscribe#9]
Don't know if it is the case now but I had problems with injected ngrx `Store`. Guess it has/had unsubscribe method and that was a case of problems. So now I am using modified version of you decorator like:
```js
export function AutoUnsubscribe(blackList = []) {
  blackList = [...blackList, 'store'];
```
Anyway, could a decorator be `@Injectable()`? (To give it provider with config)

**Comment by NetanelBasal** [comment]
It has nothing to do with ngrx/store. This decorator is not even used ngrx/store.

**Comment by FriOne** [comment]
This decorator is store agnostic It is for observables I know it.The main idea of the issue is that it would be nice to have possibility to provide global configuration.

**Comment by NetanelBasal** [comment]
Unfortunately, there is no good way to work with Angular DI through  Decorators. Thanks for the suggestion but for now, I'm closing the issue.
